version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    networks:
      - core_service_network
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - core_service_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: "mongodb://root:root@mongo:27017"
    networks:
      - core_service_network
networks:
  core_service_network:
    driver: bridge
    name: core_service_network